# Generated by Django 2.0.3 on 2018-03-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
    ]
