# Generated by Django 2.0.3 on 2018-03-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_is_del'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='描述'),
        ),
    ]
