# Generated by Django 2.0.3 on 2018-03-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180314_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='sold_nums',
            new_name='sold_num',
        ),
    ]
